/*
 * Swagger Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * API version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package petstore
// EnumNumberString : Multiple enums with underscore delim number suffix
type EnumNumberString string

// List of EnumNumberString
const (
	_1_EnumNumberString EnumNumberString = "1"
	_2_EnumNumberString EnumNumberString = "2"
)
